/*L
 * Copyright Washington University at St. Louis and Persistent Systems
 *
 * Distributed under the OSI-approved BSD 3-Clause License.
 * See http://ncip.github.com/caobr/LICENSE.txt for details.
 */

package org.cagrid.caobr.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public interface CaObrI {

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException ;

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException ;

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException ;

  public edu.wustl.caobr.Annotation[] getAllAnnotations(java.lang.String token) throws RemoteException ;

  public edu.wustl.caobr.Concept[] getAllConcepts(java.lang.String conceptName) throws RemoteException ;

  public edu.wustl.caobr.Ontology[] getAllOntologies() throws RemoteException ;

  public edu.wustl.caobr.Resource[] getAllResources() throws RemoteException ;

  public edu.wustl.caobr.Annotation[] getAnnotations(edu.wustl.caobr.Ontology[] fromOntologies,edu.wustl.caobr.Resource[] fromResources,java.lang.String token) throws RemoteException ;

  public edu.wustl.caobr.Concept[] getConcepts(edu.wustl.caobr.Ontology[] fromOntologies,java.lang.String conceptName) throws RemoteException ;

  public boolean isConcept(edu.wustl.caobr.Ontology[] fromOntologies,java.lang.String searchTerm) throws RemoteException ;

  public boolean isConceptInAnyOntology(java.lang.String searchTerm) throws RemoteException ;

  public boolean[] isConcepts(java.lang.String[] tokens,edu.wustl.caobr.Ontology[] ontologies) throws RemoteException ;

  public boolean[] isConceptsInAnyOntology(java.lang.String[] tokens) throws RemoteException ;

}

